
export const ecommerceSchema = `
=======
type EcommerceAccount{
    id: ID!
    email:String!
    username:String!
    site:String!
    password:String!
    user_id:Int!
}

input NewAccountInput{
    email:String!
    username:String!
    site:String!
    password:String!
    user_id:Int!
}

input UpdateAccountInput{
    email:String
    username:String
    password:String
}

type Query{
    accounts:EcommerceAccount!
    accountById(id:ID):EcommerceAccount
    accountBySite(site: site):EcommerceAccount

}
type Mutation{
    addAccount(input: NewAccountInput!):EcommerceAccount!
    updateAccount(id:ID!, input: UpdateAccountInput!):EcommerceAccount!
    deleteAccount(id:ID!):EcommerceAccount
}`
=======
    account:EcommerceAccount!
    accounts:[EcommerceAccount]!
    mySites(user_id:ID!):EcommerceAccount!

}

type Mutation{
    addAccount(input: NewAccountInput!):EcommerceAccount!
    updateAccount(input: UpdateAccountInput!):EcommerceAccount!
}