type User{
    id:ID!
    chatId:String!
}
type Query{
    users:[User]!
    userBychatId:User!
}
input NewUserInput{
    chatId:String!
}
type Mutation{
    register(input:NewUserInput):User!
    removeUser(chatId:String!):User
}