type User{
    id:ID!
    phoneNo:String!
}
type Query{
    users:[User]!
    userByPhoneNo:User!
=======
    user:User!
    users:[User]!
}
input NewUserInput{
    phoneNo:String!
}
type Mutation{
    register(input:NewUserInput):User!
    removeUser(id:ID!):User
}