type SavedItem{
    id:ID!
    chatId:String!
    item:String!
    description:String
    unitPrice:String
    uri:String
    image:String
    site:String
    rating:String
    dateCreated:String

}

type newItemInput{
    chatId:String!
    item:String!
    description:String
    unitPrice:String
    uri:String
    image:String
    site:String
    rating:String
}


type Query{
    mySavedItems(chatId:String!):[SavedItem]!
    savedItem(chatId:String,id:ID!):SavedItem!
    search(item:String!):SavedItem
}

type Mutation{
    saveItem(chatId:String!,input:newItemInput!):SavedItem!,
    removeItem(chatId:String!,id:ID!):SavedItem!,
    emptySavedItem(chatId:String!):SavedItem!,
    
}